package com.nischint.app.ui.screens.onboarding

import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.nischint.app.data.api.MockData
import com.nischint.app.data.api.OnboardingQuestionGenerator
import com.nischint.app.data.database.AppDatabase
import com.nischint.app.data.database.UserEntity
import com.nischint.app.data.models.OnboardingQuestion
import com.nischint.app.data.preferences.AppLanguage
import com.nischint.app.data.preferences.LanguagePreferences
import com.nischint.app.data.preferences.OnboardingPreferences
import com.nischint.app.utils.rememberCurrentLanguage
import java.util.UUID
import com.nischint.app.ui.components.NeomorphicButton
import com.nischint.app.ui.components.NeomorphicCard
import com.nischint.app.ui.theme.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.launch

@Preview(showBackground = true)
@Composable
fun OnboardingScreenPreview() {
    NischintTheme {
        OnboardingScreen(onComplete = {})
    }
}

data class ChatMessage(
    val text: String,
    val isUser: Boolean,
    val isTyping: Boolean = false
)

@Composable
fun OnboardingScreen(
    onComplete: () -> Unit
) {
    val context = LocalContext.current
    val onboardingPrefs = remember { OnboardingPreferences(context) }
    val languagePrefs = remember { LanguagePreferences(context) }
    val currentLanguage = rememberCurrentLanguage()
    val scope = rememberCoroutineScope()
    val questionGenerator = remember { OnboardingQuestionGenerator() }
    
    var userName by remember { mutableStateOf("") }  // User's name
    var showNameInput by remember { mutableStateOf(true) }  // Show name input first
    var currentQuestionIndex by remember { mutableStateOf(0) }
    var messages by remember { mutableStateOf(listOf<ChatMessage>()) }
    var showHoroscope by remember { mutableStateOf(false) }
    var isAgentTyping by remember { mutableStateOf(false) }
    var questions by remember { mutableStateOf<List<OnboardingQuestion>>(emptyList()) }
    var isAiGenerated by remember { mutableStateOf(false) }  // Track if questions are AI-generated
    var userAnswers by remember { mutableStateOf<Map<String, String>>(emptyMap()) }
    var displayedText by remember { mutableStateOf("") }  // For typing animation
    
    // Database instance
    val database = remember { AppDatabase.getDatabase(context) }
    
    val listState = rememberLazyListState()
    
    // Load questions from Gemini API
    LaunchedEffect(currentLanguage) {
        try {
            questionGenerator.generateQuestions(currentLanguage).collect { (generatedQuestions, aiGenerated) ->
                questions = generatedQuestions
                isAiGenerated = aiGenerated
            }
        } catch (e: Exception) {
            android.util.Log.e("OnboardingScreen", "Error loading questions", e)
            // Use fallback questions if API fails
            questions = MockData.onboardingQuestions
            isAiGenerated = false
        }
    }
    
    // Handle onboarding completion
    val handleComplete: () -> Unit = {
        scope.launch {
            // Save user to database
            val userId = UUID.randomUUID().toString()
            val userEntity = UserEntity(
                id = userId,
                name = userName.ifEmpty { "User" },  // Default to "User" if empty
                phone = "",  // Can be added later
                isOnboarded = true,
                language = "hi"  // Default to Hindi
            )
            database.userDao().upsertUser(userEntity)
            
            // Mark onboarding as complete
            onboardingPrefs.setOnboardingComplete(true)
        }
        onComplete()  // Navigate to home (call immediately, not in coroutine)
    }
    
    // Handle name submission
    val handleNameSubmit: (String) -> Unit = { name ->
        if (name.isNotBlank()) {
            userName = name.trim()
            showNameInput = false
        }
    }
    
    // Show greeting and first question after name is entered
    LaunchedEffect(showNameInput, questions.size) {
        if (!showNameInput && questions.isNotEmpty() && messages.isEmpty()) {
            delay(500)
            
            // Generate personalized greeting from Gemini
            val greeting = try {
                questionGenerator.generateGreeting(userName, currentLanguage)
            } catch (e: Exception) {
                android.util.Log.e("OnboardingScreen", "Error generating greeting", e)
                if (userName.isNotEmpty()) {
                    "Namaste $userName! 🙏 Main Nischint hoon, tera financial buddy!"
                } else {
                    "Namaste! 🙏 Main Nischint hoon, tera financial buddy!"
                }
            }
            
            // Show typing indicator
            isAgentTyping = true
            delay(800)
            isAgentTyping = false
            
            // Type greeting character by character (Hindi typing style)
            displayedText = ""
            for (i in greeting.indices) {
                displayedText = greeting.substring(0, i + 1)
                delay(50)  // Typing speed for Hindi characters
            }
            
            messages = messages + ChatMessage(
                text = displayedText,
                isUser = false
            )
            displayedText = ""
            
            // Wait a bit, then show first question
            delay(1000)
            
            if (questions.isNotEmpty()) {
                // Show typing indicator
                isAgentTyping = true
                delay(800)
                isAgentTyping = false
                
                // Type first question character by character
                val firstQuestion = questions[0].text
                displayedText = ""
                for (i in firstQuestion.indices) {
                    displayedText = firstQuestion.substring(0, i + 1)
                    delay(50)  // Typing speed for Hindi
                }
                
                messages = messages + ChatMessage(
                    text = displayedText,
                    isUser = false
                )
                displayedText = ""
            }
        }
    }
    
    // Scroll to bottom when new messages added
    LaunchedEffect(messages.size) {
        if (messages.isNotEmpty()) {
            listState.animateScrollToItem(messages.size - 1)
        }
    }
    
    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(Background, Surface)
                )
            )
    ) {
        // Header
        OnboardingHeader()
        
        // Chat Messages
        LazyColumn(
            state = listState,
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth()
                .padding(horizontal = 16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp),
            contentPadding = PaddingValues(vertical = 16.dp)
        ) {
            items(messages) { message ->
                ChatBubble(message = message)
            }
            
            // Show typing animation text if currently typing
            if (displayedText.isNotEmpty()) {
                item {
                    ChatBubble(message = ChatMessage(text = displayedText, isUser = false, isTyping = true))
                }
            } else if (isAgentTyping) {
                // Typing indicator (only when not showing typed text)
                item {
                    TypingIndicator()
                }
            }
        }
        
        // Name Input, Options, or Horoscope
        AnimatedContent(
            targetState = Triple(showNameInput, showHoroscope, currentQuestionIndex),
            transitionSpec = {
                fadeIn() + slideInVertically { it } togetherWith fadeOut() + slideOutVertically { -it }
            },
            label = "bottom_content"
        ) { (showingNameInput, showingHoroscope, _) ->
            when {
                showingNameInput -> {
                    // Name Input Panel
                    NameInputPanel(
                        onNameSubmit = handleNameSubmit
                    )
                }
                showingHoroscope -> {
                    HoroscopeCard(
                        horoscope = MockData.horoscope,
                        onContinue = handleComplete
                    )
                }
                currentQuestionIndex < questions.size && questions.isNotEmpty() -> {
                    val currentQuestion = questions[currentQuestionIndex]
                    OptionsPanel(
                    options = currentQuestion.options,
                    isAiGenerated = currentQuestion.isAiGenerated,  // Pass AI flag
                    onOptionSelected = { option ->
                        // Add user message
                        messages = messages + ChatMessage(text = option, isUser = true)
                        
                        // Store answer
                        userAnswers = userAnswers + (questions[currentQuestionIndex].id to option)
                        
                        // Move to next question or show horoscope
                        if (currentQuestionIndex < questions.size - 1) {
                            currentQuestionIndex++
                            // The next question will be added via LaunchedEffect
                        } else {
                            // Generate completion message
                            scope.launch {
                                val completionMsg = questionGenerator.generateCompletionMessage(userAnswers)
                                isAgentTyping = true
                                delay(1000)
                                isAgentTyping = false
                                
                                // Type completion message
                                displayedText = ""
                                for (i in completionMsg.indices) {
                                    displayedText = completionMsg.substring(0, i + 1)
                                    delay(50)
                                }
                                messages = messages + ChatMessage(text = displayedText, isUser = false)
                                displayedText = ""
                                
                                delay(1500)
                                showHoroscope = true
                            }
                        }
                    },
                    enabled = !isAgentTyping && displayedText.isEmpty()
                    )
                }
            }
        }
    }
    
    // Handle showing next question with typing animation
    LaunchedEffect(currentQuestionIndex) {
        if (currentQuestionIndex > 0 && currentQuestionIndex < questions.size && questions.isNotEmpty()) {
            delay(800)
            isAgentTyping = true
            delay(800)
            isAgentTyping = false
            
            // Type question character by character (Hindi typing style)
            val currentQuestion = questions[currentQuestionIndex]
            val questionText = if (currentQuestion.isAiGenerated) {
                "${currentQuestion.text} *"  // Add '*' for AI-generated questions
            } else {
                currentQuestion.text
            }
            displayedText = ""
            for (i in questionText.indices) {
                displayedText = questionText.substring(0, i + 1)
                delay(50)  // Typing speed for Hindi characters
            }
            
            messages = messages + ChatMessage(
                text = displayedText,
                isUser = false
            )
            displayedText = ""
        }
    }
}

@Composable
fun OnboardingHeader() {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        // Agent Avatar
        Box(
            modifier = Modifier
                .size(48.dp)
                .clip(CircleShape)
                .background(YellowPrimary),  // Yellow avatar background
            contentAlignment = Alignment.Center
        ) {
            Text(
                text = "🤖",
                fontSize = 24.sp
            )
        }
        
        Spacer(modifier = Modifier.width(12.dp))
        
        Column {
            Text(
                text = "Nischint",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold,
                color = TextWhite  // Updated to TextWhite
            )
            Text(
                text = "Tera Financial Buddy",
                style = MaterialTheme.typography.bodySmall,
                color = TextGray  // Updated to TextGray
            )
        }
    }
}

@Composable
fun ChatBubble(
    message: ChatMessage
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = if (message.isUser) Arrangement.End else Arrangement.Start
    ) {
        Surface(
            shape = RoundedCornerShape(
                topStart = 16.dp,
                topEnd = 16.dp,
                bottomStart = if (message.isUser) 16.dp else 4.dp,
                bottomEnd = if (message.isUser) 4.dp else 16.dp
            ),
            color = if (message.isUser) YellowPrimary else SurfaceDark,  // Dark theme
            shadowElevation = 2.dp,
            modifier = Modifier.widthIn(max = 280.dp)
        ) {
            Text(
                text = message.text,
                style = MaterialTheme.typography.bodyLarge,
                color = if (message.isUser) TextOnGold else TextPrimary,
                modifier = Modifier.padding(12.dp)
            )
        }
    }
}

@Composable
fun TypingIndicator() {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.Start
    ) {
        Surface(
            shape = RoundedCornerShape(16.dp),
            color = Surface,
            shadowElevation = 2.dp
        ) {
            Row(
                modifier = Modifier.padding(horizontal = 16.dp, vertical = 12.dp),
                horizontalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                repeat(3) { index ->
                    val infiniteTransition = rememberInfiniteTransition(label = "dot_$index")
                    val alpha by infiniteTransition.animateFloat(
                        initialValue = 0.3f,
                        targetValue = 1f,
                        animationSpec = infiniteRepeatable(
                            animation = tween(600, delayMillis = index * 200),
                            repeatMode = RepeatMode.Reverse
                        ),
                        label = "alpha_$index"
                    )
                    
                    Box(
                        modifier = Modifier
                            .size(8.dp)
                            .clip(CircleShape)
                            .background(TextSecondary.copy(alpha = alpha))
                    )
                }
            }
        }
    }
}

@Composable
fun NameInputPanel(
    onNameSubmit: (String) -> Unit
) {
    var nameText by remember { mutableStateOf("") }
    var isError by remember { mutableStateOf(false) }
    
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(Surface)
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text(
            text = "Pehle apna naam batao! 👋",
            style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold,
            color = TextWhite,
            textAlign = TextAlign.Center
        )
        
        Text(
            text = "Main tumhe better help kar sakun",
            style = MaterialTheme.typography.bodyMedium,
            color = TextGray,
            textAlign = TextAlign.Center
        )
        
        OutlinedTextField(
            value = nameText,
            onValueChange = { 
                nameText = it
                isError = false
            },
            label = { Text("Tumhara naam", color = TextGray) },
            placeholder = { Text("Naam likho...", color = TextGray.copy(alpha = 0.5f)) },
            singleLine = true,
            isError = isError,
            colors = OutlinedTextFieldDefaults.colors(
                focusedTextColor = TextWhite,
                unfocusedTextColor = TextWhite,
                focusedBorderColor = YellowPrimary,
                unfocusedBorderColor = BorderSubtle,
                errorBorderColor = RedDanger,
                focusedLabelColor = YellowPrimary,
                unfocusedLabelColor = TextGray
            ),
            modifier = Modifier.fillMaxWidth()
        )
        
        if (isError) {
            Text(
                text = "Kripya apna naam enter karein",
                color = RedDanger,
                style = MaterialTheme.typography.bodySmall
            )
        }
        
        NeomorphicButton(
            onClick = {
                if (nameText.isNotBlank()) {
                    onNameSubmit(nameText)
                } else {
                    isError = true
                }
            },
            modifier = Modifier.fillMaxWidth()
        ) {
            Text(
                text = "Continue →",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
        }
    }
}

@Composable
fun OptionsPanel(
    options: List<String>,
    onOptionSelected: (String) -> Unit,
    enabled: Boolean,
    isAiGenerated: Boolean = false  // Track if options are AI-generated
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(Surface)
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        options.forEach { option ->
            OptionButton(
                text = if (isAiGenerated) "$option *" else option,  // Add '*' for AI-generated
                onClick = { onOptionSelected(option) },
                enabled = enabled
            )
        }
    }
}

@Composable
fun OptionButton(
    text: String,
    onClick: () -> Unit,
    enabled: Boolean
) {
    Surface(
        onClick = onClick,
        enabled = enabled,
        shape = RoundedCornerShape(12.dp),
        color = if (enabled) Surface else Surface.copy(alpha = 0.5f),
        shadowElevation = if (enabled) 4.dp else 0.dp,
        modifier = Modifier.fillMaxWidth()
    ) {
        Text(
            text = text,
            style = MaterialTheme.typography.bodyLarge,
            color = if (enabled) TextPrimary else TextSecondary,
            modifier = Modifier.padding(16.dp),
            textAlign = TextAlign.Center
        )
    }
}

@Composable
fun HoroscopeCard(
    horoscope: com.nischint.app.data.models.HoroscopeResponse,
    onContinue: () -> Unit
) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .background(
                Brush.verticalGradient(
                    colors = listOf(YellowLight.copy(alpha = 0.3f), YellowPrimary.copy(alpha = 0.5f))  // Yellow gradient
                )
            )
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(
            text = "🔮",
            fontSize = 48.sp
        )
        
        Spacer(modifier = Modifier.height(8.dp))
        
        Text(
            text = "Tera Financial Horoscope",
            style = MaterialTheme.typography.headlineSmall,
            fontWeight = FontWeight.Bold,
            color = TextPrimary
        )
        
        Spacer(modifier = Modifier.height(16.dp))
        
        NeomorphicCard(
            modifier = Modifier.fillMaxWidth(),
            backgroundColor = Surface
        ) {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(
                    text = "Predicted Expense",
                    style = MaterialTheme.typography.labelLarge,
                    color = TextGray  // Updated to TextGray
                )
                Text(
                    text = horoscope.predictedExpense,
                    style = MaterialTheme.typography.headlineMedium,
                    fontWeight = FontWeight.Bold,
                    color = GoldPrimary
                )
                
                Spacer(modifier = Modifier.height(12.dp))
                
                Text(
                    text = "Savings Potential",
                    style = MaterialTheme.typography.labelLarge,
                    color = TextGray  // Updated to TextGray
                )
                Text(
                    text = horoscope.savingsPotential,
                    style = MaterialTheme.typography.titleLarge,
                    fontWeight = FontWeight.Bold,
                    color = TealSafe
                )
                
                Spacer(modifier = Modifier.height(12.dp))
                
                Text(
                    text = "💡 ${horoscope.tip}",
                    style = MaterialTheme.typography.bodyMedium,
                    color = TextWhite,  // Updated to TextWhite
                    textAlign = TextAlign.Center
                )
            }
        }
        
        Spacer(modifier = Modifier.height(16.dp))
        
        NeomorphicButton(
            onClick = onContinue,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text(
                text = "Chalo Shuru Karte Hai! 🚀",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
        }
    }
}
